### ISSUE TITLE
Improve `rust_source()` and related functions

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/rextendr#113]
This topic tracks a number of small issues I found in `rust_source()` which likely have no effect on the compilation process under normal conditions.

- [x] (#114) Invalid example in `rust_source()`: `dependencies` accepts `list`, not `string`;
  <details>
    <summary>code</summary>
    
     https://github.com/extendr/rextendr/blob/f8f187709497a23f8d1eb65798270cd565fcdd7a/R/source.R#L90-L92
  </details>

- [x] (#155) Use {glue} string interpolation when formatting cargo args ;
  <details>
    <summary>code</summary>
    
    https://github.com/extendr/rextendr/blob/f8f187709497a23f8d1eb65798270cd565fcdd7a/R/source.R#L266-L274
  </details>

  Blocked by:
    - https://github.com/tidyverse/glue/issues/100
    - https://github.com/tidyverse/glue/pull/217

- [x] Capture cargo output when compilation fails and produce a meaningful error message;
  <details>
    <summary>code</summary>
    
    https://github.com/extendr/rextendr/blob/f8f187709497a23f8d1eb65798270cd565fcdd7a/R/source.R#L278-L280
  </details>
  
  -  [x] (#125)  Introduce `rust_eval_deferred()` to separate Rust code compilation from execution 
  -  [x] Update `knitr` engines
  -  <s> Update to the new `{rlang}` once it gets released to incorporate this fix https://github.com/r-lib/rlang/pull/1215 </s>
  -  [x] (#155) Switch to `{processx}`, capture and parse `cargo` output. 

   

- [x] (#127) On Windows, path to build directory has back slashes, while every other path formatted with `rextendr::pretty_rel_path()` has forward slashes. Should be fixed with `normalizePath(..., winslash = "/")`
  <details>
    <summary>code</summary>
    
    https://github.com/extendr/rextendr/blob/00ce4650ee044e4b7c66ebeaecaa65c6d5ec7024/R/source.R#L113-L117
  </details>
- [x] (#127) Unused function declaration in `rust_eval_deferred()`
