### ISSUE TITLE
Tracking issue for cleanup regarding new devtools-like functions

### ISSUE THREAD

**Issue by clauswilke** [extendr/rextendr#68]
This is a tracking issue for further code cleanup regarding `rextendr::document()` etc. that was recently introduced. Let's file separate issues and then link them all here.

Things to consider/fix:

- [x] Add usethis-like interface to generate messages #62 
- [x] Remove fs dependency #69 
- [x] Remove usethis dependency #70
- [x] Don't generate `.Rd` pages for internal functions #71
- [x] Improve documentation for `rextendr::document()` #72
- [x] Document parameters `compile` in internal function `make_wrappers_externally()` #73
- [x] Write vignette on how to create and update a package with extendr code #74
- [x] **Critical bug:** Fix `pretty_rel_path()` for `rust_source()` use #79

**Comment by Ilia-Kosenkov** [comment]
I suggest including #62 in this list, it will consolidate error messages and improve user experience. With #89, it is now fairly easy and straightforward to rewrite calls to `stop()` and `message()` in terms of `ui_throw` and {cli}.

**Comment by Ilia-Kosenkov** [comment]
Everything has been done, this issue is resolved.
